FROM node:18

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY ./Backend/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY ./Backend/ ./

# Expose the port the app runs on (if applicable)
EXPOSE 3000

# Start the Node.js application
CMD ["node", "simulate_tickets.js"]