version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: postgres_tickets_db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passwordxd
      POSTGRES_DB: tickets_db
    command: ["postgres", "-c", "max_connections=200"]
    volumes:
      - postgres_data:/var/lib/postgresql/data

  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: node_backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5434
      DB_USER: postgres
      DB_PASSWORD: passwordxd
      DB_NAME: tickets_db

volumes:
  postgres_data: